services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3001
      - MONGO_USER=root
      - MONGO_PASSWORD=root
    command: npm run dev
    ports:
      - "3001:3001"  

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
